# Generated by Django 5.2.7 on 2025-10-13 06:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('image_name', models.ImageField(upload_to='images/workshop', verbose_name='تصویر')),
                ('datetime_holding', models.DateTimeField(verbose_name='تازیخ و زمان برگزاری')),
                ('place', models.CharField(max_length=20, verbose_name='مکان برگزاری')),
                ('teacher', models.CharField(max_length=20, verbose_name='نام مدرس')),
                ('information', models.TextField(max_length=200, verbose_name='اطلاعات')),
                ('registration', models.CharField(max_length=100, verbose_name='شرایط ثبت نام')),
                ('report_text', models.TextField(blank=True, max_length=200, null=True, verbose_name='متن گزارش')),
                ('view_number', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'کارگاه',
                'verbose_name_plural': 'کارگاه ها',
            },
        ),
        migrations.CreateModel(
            name='WorkshopStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20, verbose_name='وضعیت کارگاه')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'وضصعیت',
                'verbose_name_plural': 'وضعیت ها',
            },
        ),
        migrations.CreateModel(
            name='WorkshopGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/workshop', verbose_name='تصویر')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop', verbose_name='کارگاه')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویر ها',
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.workshopstatus', verbose_name='وضعیت'),
        ),
    ]
