# Generated by Django 5.2.7 on 2025-10-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='workshopstatus',
            name='slug',
        ),
    ]
