# Generated by Django 5.2.7 on 2025-10-13 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_remove_workshop_slug_remove_workshopstatus_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopgallery',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='workshops.workshop', verbose_name='کارگاه'),
        ),
    ]
