# Generated by Django 5.2.7 on 2025-10-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_alter_workshopgallery_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='information',
            field=models.TextField(max_length=400, verbose_name='اطلاعات'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='place',
            field=models.CharField(max_length=50, verbose_name='مکان برگزاری'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='registration',
            field=models.CharField(max_length=400, verbose_name='شرایط ثبت نام'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='report_text',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='متن گزارش'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
