# Generated by Django 5.2.7 on 2025-10-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_alter_workshop_information_alter_workshop_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='registration',
            field=models.TextField(max_length=400, verbose_name='شرایط ثبت نام'),
        ),
    ]
