# Generated by Django 5.2.7 on 2025-10-08 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان مکان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image_name', models.ImageField(upload_to='images/locations/', verbose_name='تصویر')),
                ('visiting_days', models.CharField(max_length=20, verbose_name='روز بازدید')),
                ('visiting_hours', models.CharField(max_length=20, verbose_name='ساعت بازدید')),
                ('ruls', models.TextField(verbose_name='قوانین و مقررات')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name=' تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان ها',
            },
        ),
        migrations.CreateModel(
            name='VisitorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام نوع بازدید کننده')),
            ],
            options={
                'verbose_name': 'نوع بازدید کننده',
                'verbose_name_plural': 'نوع بازدید کننده ها',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت بلیط')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locations', verbose_name='مکان ')),
                ('visitortype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.visitortype', verbose_name='نوع بازدید کننده')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط ها',
            },
        ),
    ]
