# Generated by Django 5.2.7 on 2025-10-10 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=50, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_seen', models.BooleanField(default=False, verbose_name='وضعیت مشاهده')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت پیام')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
