# Generated by Django 5.2.7 on 2025-10-11 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50, validators=[django.core.validators.EmailValidator(message='آدرس ایمیلی که وارد کرده اید معتبر نیست')], verbose_name='ایمیل'),
        ),
    ]
