# Generated by Django 5.2.7 on 2025-10-14 10:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('text', models.TextField(max_length=500, verbose_name='متن')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('user_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کابر ثبت کننده')),
            ],
            options={
                'verbose_name': 'خاطره ',
                'verbose_name_plural': ' خاطره  ها',
            },
        ),
        migrations.CreateModel(
            name='MemoryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to='images/memories', verbose_name='تصویر')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorygallery', to='memories.memory', verbose_name='خاطره')),
            ],
        ),
    ]
