# Generated by Django 5.2.7 on 2025-10-11 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, verbose_name='عنوان')),
                ('image_name', models.CharField(max_length=200, verbose_name='تصویر')),
                ('short_text', models.TextField(max_length=400, verbose_name='متن خلاصه')),
                ('text', models.TextField(verbose_name='متن')),
                ('key_words', models.CharField(max_length=100, verbose_name='کلمات کلیدی')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('view_number', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('slug', models.SlugField()),
                ('pdf_file', models.CharField(max_length=200, verbose_name='فایل pdf مقاله')),
            ],
            options={
                'verbose_name': 'مقاله ',
                'verbose_name_plural': ' مقاله ها',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام نوع مقاله')),
            ],
            options={
                'verbose_name': 'نوع مقاله',
                'verbose_name_plural': 'نوع مقاله ها',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='نام')),
                ('family', models.CharField(max_length=15, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل')),
                ('mobile', models.CharField(max_length=11, verbose_name='موبایل')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده ها',
            },
        ),
        migrations.CreateModel(
            name='ArticleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='تصویر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'تصویر ',
                'verbose_name_plural': ' تصویر ها',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='articletype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articletype', verbose_name='نوع مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.author', verbose_name='نوسینده'),
        ),
    ]
