# Generated by Django 5.2.7 on 2025-10-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_author_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
