# Generated by Django 5.2.7 on 2025-10-13 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegallery',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='article.article', verbose_name='مقاله'),
        ),
    ]
