# Generated by Django 5.2.7 on 2025-10-19 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
