# Generated by Django 5.2.7 on 2025-10-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_articlelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='تعداد لایک'),
        ),
    ]
